### ISSUE TITLE
USER STORY: User Friendly Navigation

### ISSUE THREAD

**Issue by KlaraMartinsson** [KlaraMartinsson/WorldWideWriters#2]
As a *site user* I can *navigate the webpage* so that *I can access what I'm looking for*

## Acceptance Criteria
- User can easily find the navigation menu
- User can navigate through the different pages
- There is a scrollbar menu in the nav menu, with continents that leads to posts about travels in that continent
- Clicking on a travel post leads to a page displaying the full post article.

## Tasks
- [ ] Create a clear navigation menu
- [ ] Create the scrollbar menu in the navigation menu
- [ ]  Make sure that all of the links are operational.
