### ISSUE TITLE
USER STORY: Submitting Comments

### ISSUE THREAD

**Issue by KlaraMartinsson** [KlaraMartinsson/WorldWideWriters#4]
As a **registered user** I can **submit comments** so that **I can engage in the post.**

## Acceptance Criteria
- Registered users can leave comments on posts.
- Registered users can edit and delete their own comments.
- Submitted comments needs admin approval.
- A confirmation message for submitted comment.

## Tasks
- [ ] Create a comment section to posts
- [ ] Ensure comments display user usernames and date.
- [ ] Give registered user full crud over their own comments.
- [ ] Implement a feature where comments only can be submitted after approval from an admin.
- [ ] Add a confirmation message when user has submitted a comment.

**Comment by KlaraMartinsson** [comment]
Implementing a search bar was not made due lack of time. This user story will be placed in "Incomplete".
