### ISSUE TITLE
USER STORY: User Profile

### ISSUE THREAD

**Issue by KlaraMartinsson** [KlaraMartinsson/WorldWideWriters#5]
As a **registered user** I can **access my profile** so that ** I can change my details and information**

## Acceptance Criteria
- Registered users can access a "Profile" section.
- Registered user can add and edit their bio.
- The user can change their log in details.
- Registered user can save posts to their profile page.

## Tasks
- [ ] Develop a "Profile" section in the registered users interface.
- [ ] Create a feature for registered users to write a bio for their profile page.
- [ ] Enable a feature for registered users to save posts to their profile page.
