### ISSUE TITLE
USER STORY: Manage posts and comments

### ISSUE THREAD

**Issue by KlaraMartinsson** [KlaraMartinsson/WorldWideWriters#7]
As a **site admin** I can **read, organize, approve and delete emissions** so that **I can manage the websites content.**

## Acceptance Criteria
- Have an admin page.
- A site admin can create, read, update and delete posts.
- A site admin can approve or delete comments.
- A site admin can organize posts within categories(continents).

## Tasks
- [ ] Create an admin page with Django.
- [ ] Ensure that all posts can be manage by the admin.
- [ ] Ensure that all comments can be manage by the admin.
- [ ] Develop a category management system.

**Comment by KlaraMartinsson** [comment]
There is one task and acceptance criteria remaining in this user story about the comments. Because of lack of time this was not prioritized and not done.
