### ISSUE TITLE
USER STORY: Save posts

### ISSUE THREAD

**Issue by KlaraMartinsson** [KlaraMartinsson/WorldWideWriters#8]
As a **registered user** I can **save posts to my profile** so that **I have easy access to the things I'm interested in.**

## Acceptance Criteria
- There is an icon nearby the post.
- If a registered user click on the icon they save the post to their profile.
- If a non registered user click on the icon they get an message telling them what it is for and asks if they want to sign up.

## Tasks
- [ ] Add an icon nearby the post.
- [ ] Develop a feature for saving posts.
- [ ] Make a feedback message.
- [ ] Verify that all of it works.
