### ISSUE TITLE
USER STORY: Search bar

### ISSUE THREAD

**Issue by KlaraMartinsson** [KlaraMartinsson/WorldWideWriters#9]
As a **site user** I can **search for the things I'm interested in** so that **it's easy to access and saves me time.**

## Acceptance Criteria
- Having a search bar that users can access from any page on the blog.
- Redirect the user to a new page after submitting the search.
- Filter out the posts with words that matches the users search.

- Acceptance criteria 4

## Tasks
- [ ] Implement a search bar in the header/navbar.
- [ ] Add a feature that redirects the user to a new page after submitting the search.
- [ ] Develop a feature that filter out the posts with words that matches the users search.

**Comment by KlaraMartinsson** [comment]
Implementing a search bar was not made due lack of time. This user story will be placed in "Incomplete".
